In [1]:
import numpy as np

In [39]:
class GradientDescent:
    def __init__(self, func, grad_func, learning_rate=0.01, max_iters=1000):
        self.func = func
        self.grad_func = grad_func
        self.learning_rate = learning_rate
        self.max_iters = max_iters

    def step(self, params, show_step=False):
        new_params = params - self.learning_rate * self.grad_func(params)
        if show_step:
            self.show_step_results(new_params)
        return new_params

    def minimize(self, init_params, delta=None, show_steps=False):
        old_params = init_params
        for _ in range(self.max_iters):
            new_params = self.step(old_params, show_step=show_steps)
            if delta is not None and np.abs(self.func(new_params) - self.func(old_params)) < delta:
                break
            old_params = new_params
        return new_params

    def show_step_results(self, params):
        print(f"Значение параметров: {params}")
        print(f"Значение функции: {self.func(params)}")

In [40]:
def func(params):
    x, y = params
    return x**2 + y**2

def grad_func(params):
    x, y = params
    return np.array([2*x, 2*y])

In [41]:
gd = GradientDescent(func, grad_func, learning_rate=0.1, max_iters=100)
gd.minimize(np.array([5.0, 5.0]), show_steps=True)

Значение параметров: [4. 4.]
Значение функции: 32.0
Значение параметров: [3.2 3.2]
Значение функции: 20.480000000000004
Значение параметров: [2.56 2.56]
Значение функции: 13.1072
Значение параметров: [2.048 2.048]
Значение функции: 8.388608
Значение параметров: [1.6384 1.6384]
Значение функции: 5.36870912
Значение параметров: [1.31072 1.31072]
Значение функции: 3.4359738368000006
Значение параметров: [1.048576 1.048576]
Значение функции: 2.199023255552001
Значение параметров: [0.8388608 0.8388608]
Значение функции: 1.4073748835532807
Значение параметров: [0.67108864 0.67108864]
Значение функции: 0.9007199254740995
Значение параметров: [0.53687091 0.53687091]
Значение функции: 0.5764607523034238
Значение параметров: [0.42949673 0.42949673]
Значение функции: 0.36893488147419123
Значение параметров: [0.34359738 0.34359738]
Значение функции: 0.23611832414348238
Значение параметров: [0.27487791 0.27487791]
Значение функции: 0.1511157274518287
Значение параметров: [0.21990233 0.21990233]
Зна

array([1.01851799e-09, 1.01851799e-09])

In [42]:
gd.step(np.array([5.0, 5.0]), True)

Значение параметров: [4. 4.]
Значение функции: 32.0


array([4., 4.])

In [43]:
# (x - 2)^2 + (y - 3)^2 - (z - 7)^2


In [44]:
def func2(params):
    x, y, z = params
    return (x - 2)**2 + (y - 3)**2 + (z - 7)**2

def grad_func2(params):
    x, y, z = params
    return np.array([2 * (x - 2), 2 * (y - 3), 2 * (z - 7)])

gd2 = GradientDescent(func2, grad_func2, learning_rate=0.1, max_iters=100)
gd2.minimize(np.array([2, 2, 2]), delta=1, show_steps=True)


Значение параметров: [2.  2.2 3. ]
Значение функции: 16.64
Значение параметров: [2.   2.36 3.8 ]
Значение функции: 10.649600000000001
Значение параметров: [2.    2.488 4.44 ]
Значение функции: 6.815744000000002
Значение параметров: [2.     2.5904 4.952 ]
Значение функции: 4.36207616
Значение параметров: [2.      2.67232 5.3616 ]
Значение функции: 2.7917287423999997
Значение параметров: [2.       2.737856 5.68928 ]
Значение функции: 1.7867063951359996
Значение параметров: [2.        2.7902848 5.951424 ]
Значение функции: 1.1434920928870396


array([2.       , 2.7902848, 5.951424 ])